server:
  port: 8020
spring:
  application:
    name: microservie.consumer.feign
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
    instance:
      preferIpAddress: true
ribbon:
  eureka:
    enabled: true